import {useEffect,useMemo,useState} from 'react';import {useParams,useNavigate} from 'react-router-dom';import {api} from '../api/client';import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell} from 'recharts';import {ErrorBox,ProgressBar,Spinner,StatusBadge,Empty} from '../components/Common'
const tabs=['Overview','Tasks','Transport','Hotels','Weather','Attractions','Itinerary','Budget','Alternatives','Action Log','Booking','Feedback']
export default function PlanDetails(){const {id}=useParams();const nav=useNavigate();const [plan,setPlan]=useState();const [tab,setTab]=useState('Overview');const [error,setError]=useState();const load=()=>{api.get(`/travel/plans/${id}`).then(r=>setPlan(r.data.data)).catch(setError)};useEffect(()=>{load()},[id]);if(error)return <ErrorBox error={error}/>;if(!plan)return <Spinner/>;return <><div className="plan-header"><div><StatusBadge status={plan.status}/><h2>{plan.title}</h2><p>{plan.request?.source} → {plan.request?.destination} · {plan.request?.traveller_count} travellers · {plan.request?.trip_duration_days} days</p></div><div className="plan-total"><small>Estimated total</small><strong>{plan.currency} {Number(plan.total_cost).toLocaleString()}</strong></div></div><ProgressBar value={plan.progress?.percentage||100}/><div className="tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="panel tab-panel">{tab==='Overview'&&<Overview plan={plan}/>} {tab==='Tasks'&&<Tasks plan={plan}/>} {tab==='Transport'&&<Options title="Transport options" items={plan.transport_options} fields={['provider','transport_type','departure_time','duration_minutes','total_price','rating','normalized_score']}/>} {tab==='Hotels'&&<Options title="Hotel options" items={plan.hotel_options} fields={['name','price_per_night','total_price','rating','distance_from_city_centre','normalized_score']}/>} {tab==='Weather'&&<Weather rows={plan.weather}/>} {tab==='Attractions'&&<Attractions rows={plan.attractions}/>} {tab==='Itinerary'&&<Itinerary days={plan.itinerary}/>} {tab==='Budget'&&<Budget data={plan.budget_breakdown}/>} {tab==='Alternatives'&&<Alternatives data={plan.alternatives}/>} {tab==='Action Log'&&<Logs id={id}/>} {tab==='Booking'&&<Booking plan={plan} reload={load}/>} {tab==='Feedback'&&<Feedback id={id}/>}</div><div className="floating-actions"><button onClick={async()=>{const r=await api.post(`/travel/plans/${id}/duplicate`);nav(`/plans/${r.data.plan_id}`)}}>Duplicate</button><button onClick={async()=>{const r=await api.post(`/travel/plans/${id}/replan`,{event_type:'HEAVY_RAIN',reason:'User requested weather-safe plan',payload:{}});nav(`/plans/${r.data.new_plan_id}`)}}>Replan for rain</button></div></>}
function Overview({plan}){
  const speak = () => {
    if (!plan.final_summary || !window.speechSynthesis) return
    window.speechSynthesis.cancel()
    const utt = new SpeechSynthesisUtterance(plan.final_summary)
    utt.lang = 'en-IN'
    window.speechSynthesis.speak(utt)
  }
  return <div className="overview-grid"><div className="summary"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8}}><h3 style={{margin:0}}>Final recommendation</h3>{plan.final_summary&&<button onClick={speak} title="Read summary aloud" style={{background:'#eef2ff',border:'none',borderRadius:8,padding:'6px 12px',cursor:'pointer',fontSize:13,fontWeight:600}}>🔊 Read Summary</button>}</div><p>{plan.final_summary}</p><h4>Selected transport</h4><p>{plan.selected_transport?.provider} · {plan.selected_transport?.transport_type} · {plan.currency} {plan.selected_transport?.total_price}</p><h4>Selected hotel</h4><p>{plan.selected_hotel?.name} · Rating {plan.selected_hotel?.rating} · {plan.currency} {plan.selected_hotel?.total_price}</p></div><div><h3>Extracted requirements</h3><dl>{Object.entries(plan.request?.extracted_requirements||{}).filter(([,v])=>v!==null&&v!==''&&(!Array.isArray(v)||v.length)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{Array.isArray(v)?v.join(', '):String(v)}</dd></div>)}</dl></div></div>}
function Tasks({plan}){return <><h3>Agent task execution</h3><table><thead><tr><th>Task</th><th>Agent</th><th>Priority</th><th>Status</th><th>Retries</th></tr></thead><tbody>{plan.progress.tasks.map(t=><tr key={t.id}><td>{t.task_name}</td><td>{t.agent_name}</td><td>{t.priority}</td><td><StatusBadge status={t.status}/></td><td>{t.retry_count}</td></tr>)}</tbody></table></>}
function Options({title,items,fields}){return <><h3>{title}</h3><div className="option-grid">{items.map((x,i)=><div key={x.id} className={`option-card ${i===0?'recommended':''}`}>{i===0&&<span className="ribbon">Recommended</span>}{fields.map(f=><div key={f}><small>{f.replaceAll('_',' ')}</small><strong>{String(x[f]??'-')}</strong></div>)}</div>)}</div></>}
function Weather({rows}){return <div className="card-grid">{rows.map(x=><div className="weather-card" key={x.id}><span className="weather-icon">{x.rain_probability>=70?'🌧️':'⛅'}</span><h4>{x.weather_date}</h4><strong>{x.condition}</strong><p>{x.minimum_temperature}°C – {x.maximum_temperature}°C</p><p>Rain: {x.rain_probability}%</p><StatusBadge status={x.outdoor_suitability}/>{x.weather_alert&&<div className="warning">{x.weather_alert}</div>}</div>)}</div>}
function Attractions({rows}){return <div className="card-grid">{rows.map(x=><div className="attraction-card" key={x.id}><span>{x.environment_type==='indoor'?'🏛️':'🌿'}</span><h4>{x.name}</h4><p>{x.category} · Rating {x.rating}</p><p>Entry: {x.entry_fee?'₹ '+x.entry_fee:'Free'}</p><StatusBadge status={x.weather_suitable?'Suitable':'Weather risk'}/></div>)}</div>}
function Itinerary({days}){return <div>{days.map(day=><div className="day" key={day.id}><h3>Day {day.day_number} · {day.itinerary_date}</h3><div className="timeline">{day.activities.map(a=><div className="timeline-item" key={a.id}><time>{a.start_time.slice(0,5)}<br/>{a.end_time.slice(0,5)}</time><div><h4>{a.activity}</h4><p>{a.location}</p><small>{a.activity_type} · Travel {a.travel_time_minutes} min · Cost ₹{a.estimated_cost}</small>{a.notes&&<em>{a.notes}</em>}</div></div>)}</div></div>)}</div>}
function Budget({data}){if(!data)return <Empty/>;const chart=[['Transport',data.transport_cost],['Hotel',data.hotel_cost],['Food',data.food_cost],['Local',data.local_transport_cost],['Attractions',data.attraction_cost],['Reserve',data.emergency_reserve]].map(([name,value])=>({name,value:Number(value)}));return <div className="chart-grid"><div><h3>Budget breakdown</h3><ResponsiveContainer width="100%" height={300}><BarChart data={chart}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#356df3" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div className="budget-summary"><span>Total budget<strong>{data.currency} {Number(data.user_budget).toLocaleString()}</strong></span><span>Estimated total<strong>{data.currency} {Number(data.total_cost).toLocaleString()}</strong></span><span>Remaining<strong>{data.currency} {Number(data.remaining_budget).toLocaleString()}</strong></span><StatusBadge status={data.within_budget?'Within budget':'Budget exceeded'}/></div></div>}
function Alternatives({data}){if(!data||!data.original_total)return <Empty text="The selected plan is already within budget."/>;return <div><h3>Cheaper alternative</h3><div className="savings">Save ₹{Number(data.savings).toLocaleString()}</div><p>Original ₹{data.original_total} → Revised ₹{data.revised_total}</p><h4>Changes</h4><ul>{data.changes.map(x=><li key={x}>{x}</li>)}</ul><h4>Trade-offs</h4><ul>{data.trade_offs.map(x=><li key={x}>{x}</li>)}</ul></div>}
function Logs({id}){const [rows,setRows]=useState([]);useEffect(()=>{api.get(`/travel/plans/${id}/action-logs`).then(r=>setRows(r.data.data))},[id]);return <><h3>Transparent action log</h3><div className="log-list">{rows.map(x=><div key={x.id}><time>{x.timestamp?.slice(11,19)}</time><div><strong>{x.agent_name}</strong><p>{x.action_performed}</p><small>{x.task_name} · {x.status}</small></div></div>)}</div></>}
function Booking({plan,reload}){const [message,setMessage]=useState('');const approve=async()=>{await api.post(`/travel/plans/${plan.id}/confirmation`,{action_type:'BOOK_PLAN',decision:'APPROVED',description:'Approve simulated transport and hotel booking'});setMessage('Approved. You can now run the simulated booking.');reload()};const book=async()=>{const r=await api.post(`/travel/plans/${plan.id}/book`,{booking_types:['TRANSPORT','HOTEL']});setMessage(r.data.message);reload()};return <div><h3>Confirmation and simulated booking</h3><p>No real payment or booking is made.</p><StatusBadge status={plan.confirmation_status}/><div className="button-row"><button onClick={approve}>Approve booking</button><button className="primary" onClick={book}>Simulate booking</button></div>{message&&<div className="success-box">{message}</div>}</div>}
function Feedback({id}){const [form,setForm]=useState({overall_rating:5,text_feedback:'',preference_tags:[]});const [sent,setSent]=useState(false);const tags=['Too expensive','Good recommendation','Prefer shorter travel','Avoid early morning','Prefer trains','Prefer indoor places','Prefer free attractions'];const submit=async()=>{await api.post(`/travel/plans/${id}/feedback`,form);setSent(true)};return sent?<div className="success-box">Feedback saved. Reusable preferences will be suggested for your approval.</div>:<div><h3>Rate this plan</h3><label>Overall rating<select value={form.overall_rating} onChange={e=>setForm({...form,overall_rating:Number(e.target.value)})}>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></label><label>Comments<textarea rows="4" value={form.text_feedback} onChange={e=>setForm({...form,text_feedback:e.target.value})}/></label><div className="tag-picker">{tags.map(t=><button key={t} className={form.preference_tags.includes(t)?'selected':''} onClick={()=>setForm({...form,preference_tags:form.preference_tags.includes(t)?form.preference_tags.filter(x=>x!==t):[...form.preference_tags,t]})}>{t}</button>)}</div><button onClick={submit}>Submit feedback</button></div>}
